#!/bin/bash
for ARG in $@
do
	if [ $ARG != "master" ]
	then
		FILES="$FILES $ARG"
	fi
done
git add $FILES
git commit -m "Ajout de :$FILES"
if [ $1 = "master" ]
then
	git push origin master
else
	git push
fi
