#!/bin/bash
for ARG in $@
do
	if [ $ARG != "master" ]
	then
		FILES="$FILES $ARG"
	else
		MASTER="OK"
	fi
done
git add $FILES
git commit -m "MaJ de :$FILES"
if [ "$MASTER" = "OK" ]
then
	git push origin master
else
	git push
fi
