#!/bin/bash
cd ~
if [ $# == "0" ]
then
	echo -e "Module : $MOD_COR\nProjet : $PROJ_COR"
elif [ $1 == "mod" ]
then
	echo "Changement de module pour $2"
	mv .zshrc .zshrc.old
	cat .zshrc.old | sed 's/MODULE='$MOD_COR'/MODULE='$2'/' > .zshrc
	source ~/.zshrc
elif [ $1 == "proj" ]
then
	echo "Changement de projet pour $2"
	mv .zshrc .zshrc.old
	cat .zshrc.old | sed 's/PROJECT='$PROJ_COR'/PROJECT='$2'/' > .zshrc
	source ~/.zshrc
elif [ $1 == 'all' ]
then
	echo "Changement de module pour $1"
	echo "Changement de projet pour $2"
	mv .zshrc .zshrc.old
	cat .zshrc.old | sed 's/MODULE='$MOD_COR'/MODULE='$2'/' | sed 's/PROJECT='$PROJ_COR'/PROJECT='$3'/' > .zshrc
	source ~/.zshrc
fi
